Add GH tests

diff --git a/.github/workflows/nf-test.yml b/.github/workflows/nf-test.yml
--- a/.github/workflows/nf-test.yml
+++ b/.github/workflows/nf-test.yml
@@ -28,6 +28,12 @@ jobs:
     - uses: nf-core/setup-nextflow@v1
     - name: Test Nextflow pipeline
       run: |
+        set -x
         cd test
-        >&2 echo "Disk space error issue!!!"
-        # nextflow run .. -profile gh -stub
+        #>&2 echo "Disk space error issue!!!"
+        for d in */
+        do
+          cd $d
+          nextflow run ../.. -profile gh -stub
+          cd ..
+        done
